module.exports = {
  setcookie: /setcookie/g,
  eval: /eval/g,
  setTimeout: /setTimeout/g,
  iframe: /iframe/g,
  unescape: /unescape/g,
  escape: /escape/g,
  classid: /classid/g,
  parseInt: /parseInt/g,
  fromCharCode: /fromCharCode/g,
  ActiveXObject: /ActiveXObject/g,
  concat: /concat/g,
  indexOf: /indexOf/g,
  substring: /substring/g,
  replace: /replace/g,
  attachEvent: /attachEvent/g,
  createElement: /createElement/g,
  getElementById: /getElementById/g,
  hexValue: /0[xX][0-9a-fA-F]+/g,
  docWrite: /document\.write/g,
  docEventListner: /document\.addEventListener/g,
  setCookie: /cookie\s*?=/g,
  singleChar: /\b\w\b/g,
  space: /\s/g,
  utfValue: /u[0-9a-z]4,8/g
}