name: Publish GPR Package

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  # Also trigger on page_build, as well as release created events
  page_build:
  release: # The release event is not triggered for draft releases
    types:
      - published
      - created
      - edited
      - prereleased

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: guardjs
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Copy static files to ./dist/
        run: cp -r ./package.json ./dist/ && cp -r ./LICENSE ./dist/ && cp -r ./README.md ./dist/ 
      - name: Publish GPR
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
