name: Publish GPR Package

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  # Also trigger on page_build, as well as release created events
  page_build:
  release: # The release event is not triggered for draft releases
    types:
      - published
      - created
      - edited
      - prereleased

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set Registry to Package.json
        run: |
          truncate -s-1 ./package.json
          echo ",\"publishConfig\":{\"registry\":\"https://npm.pkg.github.com/@guardjs\"}}" >> ./package.json
          cat "./package.json"
      - name: Test & Build
        run: |
          npm ci
          npm test
          npm run build
      - name: Copy Static Files to ./dist/
        run: cp -r ./package.json ./dist/ && cp -r ./LICENSE ./dist/ && cp -r ./README.md ./dist/ 
      - name: Set GPR Configs
        run: |
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          npm config list
      - name: Publish GPR
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
